export const zipCodeList = [
  {
    zip: "08201",
    "Zipcode name": "ABSECON, NJ",
    City: "ABSECON",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08205",
    "Zipcode name": "ABSECON, NJ",
    City: "ABSECON",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07710",
    "Zipcode name": "ADELPHIA, NJ",
    City: "ADELPHIA",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07820",
    "Zipcode name": "ALLAMUCHY, NJ",
    City: "ALLAMUCHY",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07401",
    "Zipcode name": "ALLENDALE, NJ",
    City: "ALLENDALE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07711",
    "Zipcode name": "ALLENHURST, NJ",
    City: "ALLENHURST",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08501",
    "Zipcode name": "ALLENTOWN, NJ",
    City: "ALLENTOWN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08720",
    "Zipcode name": "ALLENWOOD, NJ",
    City: "ALLENWOOD",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08001",
    "Zipcode name": "ALLOWAY, NJ",
    City: "ALLOWAY",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "07620",
    "Zipcode name": "ALPINE, NJ",
    City: "ALPINE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07821",
    "Zipcode name": "ANDOVER, NJ",
    City: "ANDOVER",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08801",
    "Zipcode name": "ANNANDALE, NJ",
    City: "ANNANDALE",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08802",
    "Zipcode name": "ASBURY, NJ",
    City: "ASBURY",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07712",
    "Zipcode name": "ASBURY PARK, NJ",
    City: "ASBURY PARK",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08004",
    "Zipcode name": "ATCO, NJ",
    City: "ATCO",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08401",
    "Zipcode name": "ATLANTIC CITY, NJ",
    City: "ATLANTIC CITY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08404",
    "Zipcode name": "ATLANTIC CITY, NJ",
    City: "ATLANTIC CITY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08405",
    "Zipcode name": "ATLANTIC CITY, NJ",
    City: "ATLANTIC CITY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07716",
    "Zipcode name": "ATLANTIC HIGHLANDS, NJ",
    City: "ATLANTIC HIGHLANDS",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08106",
    "Zipcode name": "AUDUBON, NJ",
    City: "AUDUBON",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07822",
    "Zipcode name": "AUGUSTA, NJ",
    City: "AUGUSTA",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08202",
    "Zipcode name": "AVALON, NJ",
    City: "AVALON",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07001",
    "Zipcode name": "AVENEL, NJ",
    City: "AVENEL",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07717",
    "Zipcode name": "AVON BY THE SEA, NJ",
    City: "AVON BY THE SEA",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08803",
    "Zipcode name": "BAPTISTOWN, NJ",
    City: "BAPTISTOWN",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08005",
    "Zipcode name": "BARNEGAT, NJ",
    City: "BARNEGAT",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08006",
    "Zipcode name": "BARNEGAT LIGHT, NJ",
    City: "BARNEGAT LIGHT",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08007",
    "Zipcode name": "BARRINGTON, NJ",
    City: "BARRINGTON",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07920",
    "Zipcode name": "BASKING RIDGE, NJ",
    City: "BASKING RIDGE",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07002",
    "Zipcode name": "BAYONNE, NJ",
    City: "BAYONNE",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "08721",
    "Zipcode name": "BAYVILLE, NJ",
    City: "BAYVILLE",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08008",
    "Zipcode name": "BEACH HAVEN, NJ",
    City: "BEACH HAVEN",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08722",
    "Zipcode name": "BEACHWOOD, NJ",
    City: "BEACHWOOD",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07921",
    "Zipcode name": "BEDMINSTER, NJ",
    City: "BEDMINSTER",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07718",
    "Zipcode name": "BELFORD, NJ",
    City: "BELFORD",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08502",
    "Zipcode name": "BELLE MEAD, NJ",
    City: "BELLE MEAD",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07109",
    "Zipcode name": "BELLEVILLE, NJ",
    City: "BELLEVILLE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "08031",
    "Zipcode name": "BELLMAWR, NJ",
    City: "BELLMAWR",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08099",
    "Zipcode name": "BELLMAWR, NJ",
    City: "BELLMAWR",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07715",
    "Zipcode name": "BELMAR, NJ",
    City: "BELMAR",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07719",
    "Zipcode name": "BELMAR, NJ",
    City: "BELMAR",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07823",
    "Zipcode name": "BELVIDERE, NJ",
    City: "BELVIDERE",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07621",
    "Zipcode name": "BERGENFIELD, NJ",
    City: "BERGENFIELD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07922",
    "Zipcode name": "BERKELEY HEIGHTS, NJ",
    City: "BERKELEY HEIGHTS",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08009",
    "Zipcode name": "BERLIN, NJ",
    City: "BERLIN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07924",
    "Zipcode name": "BERNARDSVILLE, NJ",
    City: "BERNARDSVILLE",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08010",
    "Zipcode name": "BEVERLY, NJ",
    City: "BEVERLY",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08011",
    "Zipcode name": "BIRMINGHAM, NJ",
    City: "BIRMINGHAM",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08012",
    "Zipcode name": "BLACKWOOD, NJ",
    City: "BLACKWOOD",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07825",
    "Zipcode name": "BLAIRSTOWN, NJ",
    City: "BLAIRSTOWN",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08504",
    "Zipcode name": "BLAWENBURG, NJ",
    City: "BLAWENBURG",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07003",
    "Zipcode name": "BLOOMFIELD, NJ",
    City: "BLOOMFIELD",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07403",
    "Zipcode name": "BLOOMINGDALE, NJ",
    City: "BLOOMINGDALE",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "08804",
    "Zipcode name": "BLOOMSBURY, NJ",
    City: "BLOOMSBURY",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07603",
    "Zipcode name": "BOGOTA, NJ",
    City: "BOGOTA",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07005",
    "Zipcode name": "BOONTON, NJ",
    City: "BOONTON",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08505",
    "Zipcode name": "BORDENTOWN, NJ",
    City: "BORDENTOWN",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08805",
    "Zipcode name": "BOUND BROOK, NJ",
    City: "BOUND BROOK",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07720",
    "Zipcode name": "BRADLEY BEACH, NJ",
    City: "BRADLEY BEACH",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07826",
    "Zipcode name": "BRANCHVILLE, NJ",
    City: "BRANCHVILLE",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07890",
    "Zipcode name": "BRANCHVILLE, NJ",
    City: "BRANCHVILLE",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08723",
    "Zipcode name": "BRICK, NJ",
    City: "BRICK",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08724",
    "Zipcode name": "BRICK, NJ",
    City: "BRICK",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08014",
    "Zipcode name": "BRIDGEPORT, NJ",
    City: "BRIDGEPORT",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08302",
    "Zipcode name": "BRIDGETON, NJ",
    City: "BRIDGETON",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08807",
    "Zipcode name": "BRIDGEWATER, NJ",
    City: "BRIDGEWATER",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08730",
    "Zipcode name": "BRIELLE, NJ",
    City: "BRIELLE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08203",
    "Zipcode name": "BRIGANTINE, NJ",
    City: "BRIGANTINE",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08808",
    "Zipcode name": "BROADWAY, NJ",
    City: "BROADWAY",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07926",
    "Zipcode name": "BROOKSIDE, NJ",
    City: "BROOKSIDE",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08015",
    "Zipcode name": "BROWNS MILLS, NJ",
    City: "BROWNS MILLS",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07828",
    "Zipcode name": "BUDD LAKE, NJ",
    City: "BUDD LAKE",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08310",
    "Zipcode name": "BUENA, NJ",
    City: "BUENA",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08016",
    "Zipcode name": "BURLINGTON, NJ",
    City: "BURLINGTON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07405",
    "Zipcode name": "BUTLER, NJ",
    City: "BUTLER",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07829",
    "Zipcode name": "BUTTZVILLE, NJ",
    City: "BUTTZVILLE",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07006",
    "Zipcode name": "CALDWELL, NJ",
    City: "CALDWELL",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07007",
    "Zipcode name": "CALDWELL, NJ",
    City: "CALDWELL",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07830",
    "Zipcode name": "CALIFON, NJ",
    City: "CALIFON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08101",
    "Zipcode name": "CAMDEN, NJ",
    City: "CAMDEN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08102",
    "Zipcode name": "CAMDEN, NJ",
    City: "CAMDEN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08103",
    "Zipcode name": "CAMDEN, NJ",
    City: "CAMDEN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08104",
    "Zipcode name": "CAMDEN, NJ",
    City: "CAMDEN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08105",
    "Zipcode name": "CAMDEN, NJ",
    City: "CAMDEN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08204",
    "Zipcode name": "CAPE MAY, NJ",
    City: "CAPE MAY",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08210",
    "Zipcode name": "CAPE MAY COURT HOUSE, NJ",
    City: "CAPE MAY COURT HOUSE",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08212",
    "Zipcode name": "CAPE MAY POINT, NJ",
    City: "CAPE MAY POINT",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07072",
    "Zipcode name": "CARLSTADT, NJ",
    City: "CARLSTADT",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07008",
    "Zipcode name": "CARTERET, NJ",
    City: "CARTERET",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08018",
    "Zipcode name": "CEDAR BROOK, NJ",
    City: "CEDAR BROOK",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07009",
    "Zipcode name": "CEDAR GROVE, NJ",
    City: "CEDAR GROVE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07927",
    "Zipcode name": "CEDAR KNOLLS, NJ",
    City: "CEDAR KNOLLS",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08311",
    "Zipcode name": "CEDARVILLE, NJ",
    City: "CEDARVILLE",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07831",
    "Zipcode name": "CHANGEWATER, NJ",
    City: "CHANGEWATER",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07928",
    "Zipcode name": "CHATHAM, NJ",
    City: "CHATHAM",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08019",
    "Zipcode name": "CHATSWORTH, NJ",
    City: "CHATSWORTH",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08002",
    "Zipcode name": "CHERRY HILL, NJ",
    City: "CHERRY HILL",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08003",
    "Zipcode name": "CHERRY HILL, NJ",
    City: "CHERRY HILL",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08034",
    "Zipcode name": "CHERRY HILL, NJ",
    City: "CHERRY HILL",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07930",
    "Zipcode name": "CHESTER, NJ",
    City: "CHESTER",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08515",
    "Zipcode name": "CHESTERFIELD, NJ",
    City: "CHESTERFIELD",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07066",
    "Zipcode name": "CLARK, NJ",
    City: "CLARK",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08020",
    "Zipcode name": "CLARKSBORO, NJ",
    City: "CLARKSBORO",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08312",
    "Zipcode name": "CLAYTON, NJ",
    City: "CLAYTON",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08021",
    "Zipcode name": "CLEMENTON, NJ",
    City: "CLEMENTON",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07010",
    "Zipcode name": "CLIFFSIDE PARK, NJ",
    City: "CLIFFSIDE PARK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07721",
    "Zipcode name": "CLIFFWOOD, NJ",
    City: "CLIFFWOOD",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07011",
    "Zipcode name": "CLIFTON, NJ",
    City: "CLIFTON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07012",
    "Zipcode name": "CLIFTON, NJ",
    City: "CLIFTON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07013",
    "Zipcode name": "CLIFTON, NJ",
    City: "CLIFTON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07014",
    "Zipcode name": "CLIFTON, NJ",
    City: "CLIFTON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07015",
    "Zipcode name": "CLIFTON, NJ",
    City: "CLIFTON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "08809",
    "Zipcode name": "CLINTON, NJ",
    City: "CLINTON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07624",
    "Zipcode name": "CLOSTER, NJ",
    City: "CLOSTER",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08108",
    "Zipcode name": "COLLINGSWOOD, NJ",
    City: "COLLINGSWOOD",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08213",
    "Zipcode name": "COLOGNE, NJ",
    City: "COLOGNE",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07067",
    "Zipcode name": "COLONIA, NJ",
    City: "COLONIA",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07722",
    "Zipcode name": "COLTS NECK, NJ",
    City: "COLTS NECK",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07832",
    "Zipcode name": "COLUMBIA, NJ",
    City: "COLUMBIA",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08022",
    "Zipcode name": "COLUMBUS, NJ",
    City: "COLUMBUS",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07961",
    "Zipcode name": "CONVENT STATION, NJ",
    City: "CONVENT STATION",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08511",
    "Zipcode name": "COOKSTOWN, NJ",
    City: "COOKSTOWN",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08512",
    "Zipcode name": "CRANBURY, NJ",
    City: "CRANBURY",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07016",
    "Zipcode name": "CRANFORD, NJ",
    City: "CRANFORD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08514",
    "Zipcode name": "CREAM RIDGE, NJ",
    City: "CREAM RIDGE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07626",
    "Zipcode name": "CRESSKILL, NJ",
    City: "CRESSKILL",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08810",
    "Zipcode name": "DAYTON, NJ",
    City: "DAYTON",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07723",
    "Zipcode name": "DEAL, NJ",
    City: "DEAL",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08023",
    "Zipcode name": "DEEPWATER, NJ",
    City: "DEEPWATER",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "08313",
    "Zipcode name": "DEERFIELD STREET, NJ",
    City: "DEERFIELD STREET",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07833",
    "Zipcode name": "DELAWARE, NJ",
    City: "DELAWARE",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08314",
    "Zipcode name": "DELMONT, NJ",
    City: "DELMONT",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07627",
    "Zipcode name": "DEMAREST, NJ",
    City: "DEMAREST",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08214",
    "Zipcode name": "DENNISVILLE, NJ",
    City: "DENNISVILLE",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07834",
    "Zipcode name": "DENVILLE, NJ",
    City: "DENVILLE",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08096",
    "Zipcode name": "DEPTFORD, NJ",
    City: "DEPTFORD",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08315",
    "Zipcode name": "DIVIDING CREEK, NJ",
    City: "DIVIDING CREEK",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08316",
    "Zipcode name": "DORCHESTER, NJ",
    City: "DORCHESTER",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08317",
    "Zipcode name": "DOROTHY, NJ",
    City: "DOROTHY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07801",
    "Zipcode name": "DOVER, NJ",
    City: "DOVER",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07802",
    "Zipcode name": "DOVER, NJ",
    City: "DOVER",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07628",
    "Zipcode name": "DUMONT, NJ",
    City: "DUMONT",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08812",
    "Zipcode name": "DUNELLEN, NJ",
    City: "DUNELLEN",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08816",
    "Zipcode name": "EAST BRUNSWICK, NJ",
    City: "EAST BRUNSWICK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07936",
    "Zipcode name": "EAST HANOVER, NJ",
    City: "EAST HANOVER",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07017",
    "Zipcode name": "EAST ORANGE, NJ",
    City: "EAST ORANGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07018",
    "Zipcode name": "EAST ORANGE, NJ",
    City: "EAST ORANGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07019",
    "Zipcode name": "EAST ORANGE, NJ",
    City: "EAST ORANGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07073",
    "Zipcode name": "EAST RUTHERFORD, NJ",
    City: "EAST RUTHERFORD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07724",
    "Zipcode name": "EATONTOWN, NJ",
    City: "EATONTOWN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07020",
    "Zipcode name": "EDGEWATER, NJ",
    City: "EDGEWATER",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08817",
    "Zipcode name": "EDISON, NJ",
    City: "EDISON",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08818",
    "Zipcode name": "EDISON, NJ",
    City: "EDISON",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08820",
    "Zipcode name": "EDISON, NJ",
    City: "EDISON",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08837",
    "Zipcode name": "EDISON, NJ",
    City: "EDISON",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08899",
    "Zipcode name": "EDISON, NJ",
    City: "EDISON",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08215",
    "Zipcode name": "EGG HARBOR CITY, NJ",
    City: "EGG HARBOR CITY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08234",
    "Zipcode name": "EGG HARBOR TOWNSHIP, NJ",
    City: "EGG HARBOR TOWNSHIP",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07201",
    "Zipcode name": "ELIZABETH, NJ",
    City: "ELIZABETH",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07202",
    "Zipcode name": "ELIZABETH, NJ",
    City: "ELIZABETH",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07207",
    "Zipcode name": "ELIZABETH, NJ",
    City: "ELIZABETH",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07208",
    "Zipcode name": "ELIZABETH, NJ",
    City: "ELIZABETH",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07206",
    "Zipcode name": "ELIZABETHPORT, NJ",
    City: "ELIZABETHPORT",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08318",
    "Zipcode name": "ELMER, NJ",
    City: "ELMER",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "07407",
    "Zipcode name": "ELMWOOD PARK, NJ",
    City: "ELMWOOD PARK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08217",
    "Zipcode name": "ELWOOD, NJ",
    City: "ELWOOD",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07630",
    "Zipcode name": "EMERSON, NJ",
    City: "EMERSON",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07631",
    "Zipcode name": "ENGLEWOOD, NJ",
    City: "ENGLEWOOD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07632",
    "Zipcode name": "ENGLEWOOD CLIFFS, NJ",
    City: "ENGLEWOOD CLIFFS",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07726",
    "Zipcode name": "ENGLISHTOWN, NJ",
    City: "ENGLISHTOWN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07021",
    "Zipcode name": "ESSEX FELLS, NJ",
    City: "ESSEX FELLS",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "08319",
    "Zipcode name": "ESTELL MANOR, NJ",
    City: "ESTELL MANOR",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08025",
    "Zipcode name": "EWAN, NJ",
    City: "EWAN",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07704",
    "Zipcode name": "FAIR HAVEN, NJ",
    City: "FAIR HAVEN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07410",
    "Zipcode name": "FAIR LAWN, NJ",
    City: "FAIR LAWN",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07004",
    "Zipcode name": "FAIRFIELD, NJ",
    City: "FAIRFIELD",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "08320",
    "Zipcode name": "FAIRTON, NJ",
    City: "FAIRTON",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07022",
    "Zipcode name": "FAIRVIEW, NJ",
    City: "FAIRVIEW",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07023",
    "Zipcode name": "FANWOOD, NJ",
    City: "FANWOOD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07931",
    "Zipcode name": "FAR HILLS, NJ",
    City: "FAR HILLS",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07727",
    "Zipcode name": "FARMINGDALE, NJ",
    City: "FARMINGDALE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08821",
    "Zipcode name": "FLAGTOWN, NJ",
    City: "FLAGTOWN",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07836",
    "Zipcode name": "FLANDERS, NJ",
    City: "FLANDERS",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08822",
    "Zipcode name": "FLEMINGTON, NJ",
    City: "FLEMINGTON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08518",
    "Zipcode name": "FLORENCE, NJ",
    City: "FLORENCE",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07932",
    "Zipcode name": "FLORHAM PARK, NJ",
    City: "FLORHAM PARK",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08863",
    "Zipcode name": "FORDS, NJ",
    City: "FORDS",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08731",
    "Zipcode name": "FORKED RIVER, NJ",
    City: "FORKED RIVER",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08640",
    "Zipcode name": "FORT DIX, NJ",
    City: "FORT DIX",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07024",
    "Zipcode name": "FORT LEE, NJ",
    City: "FORT LEE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07703",
    "Zipcode name": "FORT MONMOUTH, NJ",
    City: "FORT MONMOUTH",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08321",
    "Zipcode name": "FORTESCUE, NJ",
    City: "FORTESCUE",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07416",
    "Zipcode name": "FRANKLIN, NJ",
    City: "FRANKLIN",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07417",
    "Zipcode name": "FRANKLIN LAKES, NJ",
    City: "FRANKLIN LAKES",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08823",
    "Zipcode name": "FRANKLIN PARK, NJ",
    City: "FRANKLIN PARK",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08322",
    "Zipcode name": "FRANKLINVILLE, NJ",
    City: "FRANKLINVILLE",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07728",
    "Zipcode name": "FREEHOLD, NJ",
    City: "FREEHOLD",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08825",
    "Zipcode name": "FRENCHTOWN, NJ",
    City: "FRENCHTOWN",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07026",
    "Zipcode name": "GARFIELD, NJ",
    City: "GARFIELD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07027",
    "Zipcode name": "GARWOOD, NJ",
    City: "GARWOOD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08026",
    "Zipcode name": "GIBBSBORO, NJ",
    City: "GIBBSBORO",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08027",
    "Zipcode name": "GIBBSTOWN, NJ",
    City: "GIBBSTOWN",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07933",
    "Zipcode name": "GILLETTE, NJ",
    City: "GILLETTE",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07934",
    "Zipcode name": "GLADSTONE, NJ",
    City: "GLADSTONE",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08028",
    "Zipcode name": "GLASSBORO, NJ",
    City: "GLASSBORO",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08826",
    "Zipcode name": "GLEN GARDNER, NJ",
    City: "GLEN GARDNER",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07028",
    "Zipcode name": "GLEN RIDGE, NJ",
    City: "GLEN RIDGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07452",
    "Zipcode name": "GLEN ROCK, NJ",
    City: "GLEN ROCK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08029",
    "Zipcode name": "GLENDORA, NJ",
    City: "GLENDORA",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07418",
    "Zipcode name": "GLENWOOD, NJ",
    City: "GLENWOOD",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08030",
    "Zipcode name": "GLOUCESTER CITY, NJ",
    City: "GLOUCESTER CITY",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08218",
    "Zipcode name": "GOSHEN, NJ",
    City: "GOSHEN",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07838",
    "Zipcode name": "GREAT MEADOWS, NJ",
    City: "GREAT MEADOWS",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08219",
    "Zipcode name": "GREEN CREEK, NJ",
    City: "GREEN CREEK",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07935",
    "Zipcode name": "GREEN VILLAGE, NJ",
    City: "GREEN VILLAGE",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07839",
    "Zipcode name": "GREENDELL, NJ",
    City: "GREENDELL",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08323",
    "Zipcode name": "GREENWICH, NJ",
    City: "GREENWICH",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08032",
    "Zipcode name": "GRENLOCH, NJ",
    City: "GRENLOCH",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07601",
    "Zipcode name": "HACKENSACK, NJ",
    City: "HACKENSACK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07602",
    "Zipcode name": "HACKENSACK, NJ",
    City: "HACKENSACK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07840",
    "Zipcode name": "HACKETTSTOWN, NJ",
    City: "HACKETTSTOWN",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08035",
    "Zipcode name": "HADDON HEIGHTS, NJ",
    City: "HADDON HEIGHTS",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08033",
    "Zipcode name": "HADDONFIELD, NJ",
    City: "HADDONFIELD",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08036",
    "Zipcode name": "HAINESPORT, NJ",
    City: "HAINESPORT",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07508",
    "Zipcode name": "HALEDON, NJ",
    City: "HALEDON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07538",
    "Zipcode name": "HALEDON, NJ",
    City: "HALEDON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07419",
    "Zipcode name": "HAMBURG, NJ",
    City: "HAMBURG",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08037",
    "Zipcode name": "HAMMONTON, NJ",
    City: "HAMMONTON",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08827",
    "Zipcode name": "HAMPTON, NJ",
    City: "HAMPTON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08038",
    "Zipcode name": "HANCOCKS BRIDGE, NJ",
    City: "HANCOCKS BRIDGE",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "07640",
    "Zipcode name": "HARRINGTON PARK, NJ",
    City: "HARRINGTON PARK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07029",
    "Zipcode name": "HARRISON, NJ",
    City: "HARRISON",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "08039",
    "Zipcode name": "HARRISONVILLE, NJ",
    City: "HARRISONVILLE",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07604",
    "Zipcode name": "HASBROUCK HEIGHTS, NJ",
    City: "HASBROUCK HEIGHTS",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07420",
    "Zipcode name": "HASKELL, NJ",
    City: "HASKELL",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07641",
    "Zipcode name": "HAWORTH, NJ",
    City: "HAWORTH",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07506",
    "Zipcode name": "HAWTHORNE, NJ",
    City: "HAWTHORNE",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07507",
    "Zipcode name": "HAWTHORNE, NJ",
    City: "HAWTHORNE",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07730",
    "Zipcode name": "HAZLET, NJ",
    City: "HAZLET",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08324",
    "Zipcode name": "HEISLERVILLE, NJ",
    City: "HEISLERVILLE",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08828",
    "Zipcode name": "HELMETTA, NJ",
    City: "HELMETTA",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07421",
    "Zipcode name": "HEWITT, NJ",
    City: "HEWITT",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07842",
    "Zipcode name": "HIBERNIA, NJ",
    City: "HIBERNIA",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08829",
    "Zipcode name": "HIGH BRIDGE, NJ",
    City: "HIGH BRIDGE",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07422",
    "Zipcode name": "HIGHLAND LAKES, NJ",
    City: "HIGHLAND LAKES",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08904",
    "Zipcode name": "HIGHLAND PARK, NJ",
    City: "HIGHLAND PARK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07732",
    "Zipcode name": "HIGHLANDS, NJ",
    City: "HIGHLANDS",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08520",
    "Zipcode name": "HIGHTSTOWN, NJ",
    City: "HIGHTSTOWN",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08844",
    "Zipcode name": "HILLSBOROUGH, NJ",
    City: "HILLSBOROUGH",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07642",
    "Zipcode name": "HILLSDALE, NJ",
    City: "HILLSDALE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07205",
    "Zipcode name": "HILLSIDE, NJ",
    City: "HILLSIDE",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07423",
    "Zipcode name": "HO HO KUS, NJ",
    City: "HO HO KUS",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07030",
    "Zipcode name": "HOBOKEN, NJ",
    City: "HOBOKEN",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07733",
    "Zipcode name": "HOLMDEL, NJ",
    City: "HOLMDEL",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07843",
    "Zipcode name": "HOPATCONG, NJ",
    City: "HOPATCONG",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07844",
    "Zipcode name": "HOPE, NJ",
    City: "HOPE",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08525",
    "Zipcode name": "HOPEWELL, NJ",
    City: "HOPEWELL",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "07731",
    "Zipcode name": "HOWELL, NJ",
    City: "HOWELL",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08526",
    "Zipcode name": "IMLAYSTOWN, NJ",
    City: "IMLAYSTOWN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07845",
    "Zipcode name": "IRONIA, NJ",
    City: "IRONIA",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07111",
    "Zipcode name": "IRVINGTON, NJ",
    City: "IRVINGTON",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "08830",
    "Zipcode name": "ISELIN, NJ",
    City: "ISELIN",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08732",
    "Zipcode name": "ISLAND HEIGHTS, NJ",
    City: "ISLAND HEIGHTS",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08527",
    "Zipcode name": "JACKSON, NJ",
    City: "JACKSON",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07097",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07302",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07303",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07304",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07305",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07306",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07307",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07308",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07310",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07311",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07395",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07399",
    "Zipcode name": "JERSEY CITY, NJ",
    City: "JERSEY CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "08041",
    "Zipcode name": "JOBSTOWN, NJ",
    City: "JOBSTOWN",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07846",
    "Zipcode name": "JOHNSONBURG, NJ",
    City: "JOHNSONBURG",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08042",
    "Zipcode name": "JULIUSTOWN, NJ",
    City: "JULIUSTOWN",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07734",
    "Zipcode name": "KEANSBURG, NJ",
    City: "KEANSBURG",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07032",
    "Zipcode name": "KEARNY, NJ",
    City: "KEARNY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07099",
    "Zipcode name": "KEARNY, NJ",
    City: "KEARNY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "08832",
    "Zipcode name": "KEASBEY, NJ",
    City: "KEASBEY",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08824",
    "Zipcode name": "KENDALL PARK, NJ",
    City: "KENDALL PARK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07033",
    "Zipcode name": "KENILWORTH, NJ",
    City: "KENILWORTH",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07847",
    "Zipcode name": "KENVIL, NJ",
    City: "KENVIL",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07735",
    "Zipcode name": "KEYPORT, NJ",
    City: "KEYPORT",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08528",
    "Zipcode name": "KINGSTON, NJ",
    City: "KINGSTON",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07848",
    "Zipcode name": "LAFAYETTE, NJ",
    City: "LAFAYETTE",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07034",
    "Zipcode name": "LAKE HIAWATHA, NJ",
    City: "LAKE HIAWATHA",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07849",
    "Zipcode name": "LAKE HOPATCONG, NJ",
    City: "LAKE HOPATCONG",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08733",
    "Zipcode name": "LAKEHURST, NJ",
    City: "LAKEHURST",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08701",
    "Zipcode name": "LAKEWOOD, NJ",
    City: "LAKEWOOD",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08530",
    "Zipcode name": "LAMBERTVILLE, NJ",
    City: "LAMBERTVILLE",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07850",
    "Zipcode name": "LANDING, NJ",
    City: "LANDING",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08326",
    "Zipcode name": "LANDISVILLE, NJ",
    City: "LANDISVILLE",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08734",
    "Zipcode name": "LANOKA HARBOR, NJ",
    City: "LANOKA HARBOR",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08735",
    "Zipcode name": "LAVALLETTE, NJ",
    City: "LAVALLETTE",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08045",
    "Zipcode name": "LAWNSIDE, NJ",
    City: "LAWNSIDE",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08648",
    "Zipcode name": "LAWRENCE TOWNSHIP, NJ",
    City: "LAWRENCE TOWNSHIP",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "07851",
    "Zipcode name": "LAYTON, NJ",
    City: "LAYTON",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08833",
    "Zipcode name": "LEBANON, NJ",
    City: "LEBANON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07852",
    "Zipcode name": "LEDGEWOOD, NJ",
    City: "LEDGEWOOD",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08220",
    "Zipcode name": "LEEDS POINT, NJ",
    City: "LEEDS POINT",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08327",
    "Zipcode name": "LEESBURG, NJ",
    City: "LEESBURG",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07737",
    "Zipcode name": "LEONARDO, NJ",
    City: "LEONARDO",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07605",
    "Zipcode name": "LEONIA, NJ",
    City: "LEONIA",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07938",
    "Zipcode name": "LIBERTY CORNER, NJ",
    City: "LIBERTY CORNER",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07035",
    "Zipcode name": "LINCOLN PARK, NJ",
    City: "LINCOLN PARK",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07738",
    "Zipcode name": "LINCROFT, NJ",
    City: "LINCROFT",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07036",
    "Zipcode name": "LINDEN, NJ",
    City: "LINDEN",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08221",
    "Zipcode name": "LINWOOD, NJ",
    City: "LINWOOD",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07424",
    "Zipcode name": "LITTLE FALLS, NJ",
    City: "LITTLE FALLS",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07643",
    "Zipcode name": "LITTLE FERRY, NJ",
    City: "LITTLE FERRY",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07739",
    "Zipcode name": "LITTLE SILVER, NJ",
    City: "LITTLE SILVER",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07039",
    "Zipcode name": "LIVINGSTON, NJ",
    City: "LIVINGSTON",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07644",
    "Zipcode name": "LODI, NJ",
    City: "LODI",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07740",
    "Zipcode name": "LONG BRANCH, NJ",
    City: "LONG BRANCH",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07853",
    "Zipcode name": "LONG VALLEY, NJ",
    City: "LONG VALLEY",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08403",
    "Zipcode name": "LONGPORT, NJ",
    City: "LONGPORT",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08048",
    "Zipcode name": "LUMBERTON, NJ",
    City: "LUMBERTON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07071",
    "Zipcode name": "LYNDHURST, NJ",
    City: "LYNDHURST",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07939",
    "Zipcode name": "LYONS, NJ",
    City: "LYONS",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07940",
    "Zipcode name": "MADISON, NJ",
    City: "MADISON",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08049",
    "Zipcode name": "MAGNOLIA, NJ",
    City: "MAGNOLIA",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07430",
    "Zipcode name": "MAHWAH, NJ",
    City: "MAHWAH",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07495",
    "Zipcode name": "MAHWAH, NJ",
    City: "MAHWAH",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08328",
    "Zipcode name": "MALAGA, NJ",
    City: "MALAGA",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08050",
    "Zipcode name": "MANAHAWKIN, NJ",
    City: "MANAHAWKIN",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08736",
    "Zipcode name": "MANASQUAN, NJ",
    City: "MANASQUAN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08759",
    "Zipcode name": "MANCHESTER TOWNSHIP, NJ",
    City: "MANCHESTER TOWNSHIP",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08738",
    "Zipcode name": "MANTOLOKING, NJ",
    City: "MANTOLOKING",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08051",
    "Zipcode name": "MANTUA, NJ",
    City: "MANTUA",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08835",
    "Zipcode name": "MANVILLE, NJ",
    City: "MANVILLE",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08052",
    "Zipcode name": "MAPLE SHADE, NJ",
    City: "MAPLE SHADE",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07040",
    "Zipcode name": "MAPLEWOOD, NJ",
    City: "MAPLEWOOD",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "08402",
    "Zipcode name": "MARGATE CITY, NJ",
    City: "MARGATE CITY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07746",
    "Zipcode name": "MARLBORO, NJ",
    City: "MARLBORO",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08053",
    "Zipcode name": "MARLTON, NJ",
    City: "MARLTON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08223",
    "Zipcode name": "MARMORA, NJ",
    City: "MARMORA",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08836",
    "Zipcode name": "MARTINSVILLE, NJ",
    City: "MARTINSVILLE",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07747",
    "Zipcode name": "MATAWAN, NJ",
    City: "MATAWAN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08329",
    "Zipcode name": "MAURICETOWN, NJ",
    City: "MAURICETOWN",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08330",
    "Zipcode name": "MAYS LANDING, NJ",
    City: "MAYS LANDING",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07607",
    "Zipcode name": "MAYWOOD, NJ",
    City: "MAYWOOD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07428",
    "Zipcode name": "MC AFEE, NJ",
    City: "MC AFEE",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08055",
    "Zipcode name": "MEDFORD, NJ",
    City: "MEDFORD",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07945",
    "Zipcode name": "MENDHAM, NJ",
    City: "MENDHAM",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08109",
    "Zipcode name": "MERCHANTVILLE, NJ",
    City: "MERCHANTVILLE",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08840",
    "Zipcode name": "METUCHEN, NJ",
    City: "METUCHEN",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08056",
    "Zipcode name": "MICKLETON, NJ",
    City: "MICKLETON",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08846",
    "Zipcode name": "MIDDLESEX, NJ",
    City: "MIDDLESEX",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07748",
    "Zipcode name": "MIDDLETOWN, NJ",
    City: "MIDDLETOWN",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07855",
    "Zipcode name": "MIDDLEVILLE, NJ",
    City: "MIDDLEVILLE",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07432",
    "Zipcode name": "MIDLAND PARK, NJ",
    City: "MIDLAND PARK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08848",
    "Zipcode name": "MILFORD, NJ",
    City: "MILFORD",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07041",
    "Zipcode name": "MILLBURN, NJ",
    City: "MILLBURN",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07946",
    "Zipcode name": "MILLINGTON, NJ",
    City: "MILLINGTON",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08510",
    "Zipcode name": "MILLSTONE TOWNSHIP, NJ",
    City: "MILLSTONE TOWNSHIP",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08535",
    "Zipcode name": "MILLSTONE TOWNSHIP, NJ",
    City: "MILLSTONE TOWNSHIP",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08850",
    "Zipcode name": "MILLTOWN, NJ",
    City: "MILLTOWN",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08332",
    "Zipcode name": "MILLVILLE, NJ",
    City: "MILLVILLE",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08340",
    "Zipcode name": "MILMAY, NJ",
    City: "MILMAY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07803",
    "Zipcode name": "MINE HILL, NJ",
    City: "MINE HILL",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08341",
    "Zipcode name": "MINOTOLA, NJ",
    City: "MINOTOLA",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08342",
    "Zipcode name": "MIZPAH, NJ",
    City: "MIZPAH",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07750",
    "Zipcode name": "MONMOUTH BEACH, NJ",
    City: "MONMOUTH BEACH",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08852",
    "Zipcode name": "MONMOUTH JUNCTION, NJ",
    City: "MONMOUTH JUNCTION",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08831",
    "Zipcode name": "MONROE TOWNSHIP, NJ",
    City: "MONROE TOWNSHIP",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08343",
    "Zipcode name": "MONROEVILLE, NJ",
    City: "MONROEVILLE",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "07827",
    "Zipcode name": "MONTAGUE, NJ",
    City: "MONTAGUE",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07042",
    "Zipcode name": "MONTCLAIR, NJ",
    City: "MONTCLAIR",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07043",
    "Zipcode name": "MONTCLAIR, NJ",
    City: "MONTCLAIR",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07645",
    "Zipcode name": "MONTVALE, NJ",
    City: "MONTVALE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07045",
    "Zipcode name": "MONTVILLE, NJ",
    City: "MONTVILLE",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07074",
    "Zipcode name": "MOONACHIE, NJ",
    City: "MOONACHIE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08057",
    "Zipcode name": "MOORESTOWN, NJ",
    City: "MOORESTOWN",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07751",
    "Zipcode name": "MORGANVILLE, NJ",
    City: "MORGANVILLE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07950",
    "Zipcode name": "MORRIS PLAINS, NJ",
    City: "MORRIS PLAINS",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07960",
    "Zipcode name": "MORRISTOWN, NJ",
    City: "MORRISTOWN",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07962",
    "Zipcode name": "MORRISTOWN, NJ",
    City: "MORRISTOWN",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07963",
    "Zipcode name": "MORRISTOWN, NJ",
    City: "MORRISTOWN",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07856",
    "Zipcode name": "MOUNT ARLINGTON, NJ",
    City: "MOUNT ARLINGTON",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08059",
    "Zipcode name": "MOUNT EPHRAIM, NJ",
    City: "MOUNT EPHRAIM",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07970",
    "Zipcode name": "MOUNT FREEDOM, NJ",
    City: "MOUNT FREEDOM",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08060",
    "Zipcode name": "MOUNT HOLLY, NJ",
    City: "MOUNT HOLLY",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08054",
    "Zipcode name": "MOUNT LAUREL, NJ",
    City: "MOUNT LAUREL",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08061",
    "Zipcode name": "MOUNT ROYAL, NJ",
    City: "MOUNT ROYAL",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07878",
    "Zipcode name": "MOUNT TABOR, NJ",
    City: "MOUNT TABOR",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07046",
    "Zipcode name": "MOUNTAIN LAKES, NJ",
    City: "MOUNTAIN LAKES",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07092",
    "Zipcode name": "MOUNTAINSIDE, NJ",
    City: "MOUNTAINSIDE",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08062",
    "Zipcode name": "MULLICA HILL, NJ",
    City: "MULLICA HILL",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08063",
    "Zipcode name": "NATIONAL PARK, NJ",
    City: "NATIONAL PARK",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07752",
    "Zipcode name": "NAVESINK, NJ",
    City: "NAVESINK",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07753",
    "Zipcode name": "NEPTUNE, NJ",
    City: "NEPTUNE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07754",
    "Zipcode name": "NEPTUNE, NJ",
    City: "NEPTUNE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08853",
    "Zipcode name": "NESHANIC STATION, NJ",
    City: "NESHANIC STATION",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07857",
    "Zipcode name": "NETCONG, NJ",
    City: "NETCONG",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08901",
    "Zipcode name": "NEW BRUNSWICK, NJ",
    City: "NEW BRUNSWICK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08903",
    "Zipcode name": "NEW BRUNSWICK, NJ",
    City: "NEW BRUNSWICK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08906",
    "Zipcode name": "NEW BRUNSWICK, NJ",
    City: "NEW BRUNSWICK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08933",
    "Zipcode name": "NEW BRUNSWICK, NJ",
    City: "NEW BRUNSWICK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08533",
    "Zipcode name": "NEW EGYPT, NJ",
    City: "NEW EGYPT",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08224",
    "Zipcode name": "NEW GRETNA, NJ",
    City: "NEW GRETNA",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08064",
    "Zipcode name": "NEW LISBON, NJ",
    City: "NEW LISBON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07646",
    "Zipcode name": "NEW MILFORD, NJ",
    City: "NEW MILFORD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07974",
    "Zipcode name": "NEW PROVIDENCE, NJ",
    City: "NEW PROVIDENCE",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07976",
    "Zipcode name": "NEW VERNON, NJ",
    City: "NEW VERNON",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07101",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07102",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07103",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07104",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07105",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07106",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07107",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07108",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07112",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07114",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07193",
    "Zipcode name": "NEWARK, NJ",
    City: "NEWARK",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "08344",
    "Zipcode name": "NEWFIELD, NJ",
    City: "NEWFIELD",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07435",
    "Zipcode name": "NEWFOUNDLAND, NJ",
    City: "NEWFOUNDLAND",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "08345",
    "Zipcode name": "NEWPORT, NJ",
    City: "NEWPORT",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07860",
    "Zipcode name": "NEWTON, NJ",
    City: "NEWTON",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08346",
    "Zipcode name": "NEWTONVILLE, NJ",
    City: "NEWTONVILLE",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08347",
    "Zipcode name": "NORMA, NJ",
    City: "NORMA",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "08739",
    "Zipcode name": "NORMANDY BEACH, NJ",
    City: "NORMANDY BEACH",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07031",
    "Zipcode name": "NORTH ARLINGTON, NJ",
    City: "NORTH ARLINGTON",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07047",
    "Zipcode name": "NORTH BERGEN, NJ",
    City: "NORTH BERGEN",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "08902",
    "Zipcode name": "NORTH BRUNSWICK, NJ",
    City: "NORTH BRUNSWICK",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08225",
    "Zipcode name": "NORTHFIELD, NJ",
    City: "NORTHFIELD",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07647",
    "Zipcode name": "NORTHVALE, NJ",
    City: "NORTHVALE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07648",
    "Zipcode name": "NORWOOD, NJ",
    City: "NORWOOD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07110",
    "Zipcode name": "NUTLEY, NJ",
    City: "NUTLEY",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07438",
    "Zipcode name": "OAK RIDGE, NJ",
    City: "OAK RIDGE",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07755",
    "Zipcode name": "OAKHURST, NJ",
    City: "OAKHURST",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07436",
    "Zipcode name": "OAKLAND, NJ",
    City: "OAKLAND",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08107",
    "Zipcode name": "OAKLYN, NJ",
    City: "OAKLYN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08226",
    "Zipcode name": "OCEAN CITY, NJ",
    City: "OCEAN CITY",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08740",
    "Zipcode name": "OCEAN GATE, NJ",
    City: "OCEAN GATE",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07756",
    "Zipcode name": "OCEAN GROVE, NJ",
    City: "OCEAN GROVE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08230",
    "Zipcode name": "OCEAN VIEW, NJ",
    City: "OCEAN VIEW",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07757",
    "Zipcode name": "OCEANPORT, NJ",
    City: "OCEANPORT",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08231",
    "Zipcode name": "OCEANVILLE, NJ",
    City: "OCEANVILLE",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07439",
    "Zipcode name": "OGDENSBURG, NJ",
    City: "OGDENSBURG",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08857",
    "Zipcode name": "OLD BRIDGE, NJ",
    City: "OLD BRIDGE",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08858",
    "Zipcode name": "OLDWICK, NJ",
    City: "OLDWICK",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07649",
    "Zipcode name": "ORADELL, NJ",
    City: "ORADELL",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07050",
    "Zipcode name": "ORANGE, NJ",
    City: "ORANGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07051",
    "Zipcode name": "ORANGE, NJ",
    City: "ORANGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07863",
    "Zipcode name": "OXFORD, NJ",
    City: "OXFORD",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07650",
    "Zipcode name": "PALISADES PARK, NJ",
    City: "PALISADES PARK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08065",
    "Zipcode name": "PALMYRA, NJ",
    City: "PALMYRA",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07652",
    "Zipcode name": "PARAMUS, NJ",
    City: "PARAMUS",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07653",
    "Zipcode name": "PARAMUS, NJ",
    City: "PARAMUS",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07656",
    "Zipcode name": "PARK RIDGE, NJ",
    City: "PARK RIDGE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08859",
    "Zipcode name": "PARLIN, NJ",
    City: "PARLIN",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07054",
    "Zipcode name": "PARSIPPANY, NJ",
    City: "PARSIPPANY",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07055",
    "Zipcode name": "PASSAIC, NJ",
    City: "PASSAIC",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07501",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07502",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07503",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07504",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07505",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07509",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07510",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07513",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07514",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07522",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07524",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07543",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07544",
    "Zipcode name": "PATERSON, NJ",
    City: "PATERSON",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "08066",
    "Zipcode name": "PAULSBORO, NJ",
    City: "PAULSBORO",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07977",
    "Zipcode name": "PEAPACK, NJ",
    City: "PEAPACK",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08067",
    "Zipcode name": "PEDRICKTOWN, NJ",
    City: "PEDRICKTOWN",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "08068",
    "Zipcode name": "PEMBERTON, NJ",
    City: "PEMBERTON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08534",
    "Zipcode name": "PENNINGTON, NJ",
    City: "PENNINGTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08069",
    "Zipcode name": "PENNS GROVE, NJ",
    City: "PENNS GROVE",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "08110",
    "Zipcode name": "PENNSAUKEN, NJ",
    City: "PENNSAUKEN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08070",
    "Zipcode name": "PENNSVILLE, NJ",
    City: "PENNSVILLE",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "07440",
    "Zipcode name": "PEQUANNOCK, NJ",
    City: "PEQUANNOCK",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08861",
    "Zipcode name": "PERTH AMBOY, NJ",
    City: "PERTH AMBOY",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08862",
    "Zipcode name": "PERTH AMBOY, NJ",
    City: "PERTH AMBOY",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08865",
    "Zipcode name": "PHILLIPSBURG, NJ",
    City: "PHILLIPSBURG",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07806",
    "Zipcode name": "PICATINNY ARSENAL, NJ",
    City: "PICATINNY ARSENAL",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08741",
    "Zipcode name": "PINE BEACH, NJ",
    City: "PINE BEACH",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07058",
    "Zipcode name": "PINE BROOK, NJ",
    City: "PINE BROOK",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08854",
    "Zipcode name": "PISCATAWAY, NJ",
    City: "PISCATAWAY",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08855",
    "Zipcode name": "PISCATAWAY, NJ",
    City: "PISCATAWAY",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08071",
    "Zipcode name": "PITMAN, NJ",
    City: "PITMAN",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08867",
    "Zipcode name": "PITTSTOWN, NJ",
    City: "PITTSTOWN",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07060",
    "Zipcode name": "PLAINFIELD, NJ",
    City: "PLAINFIELD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07061",
    "Zipcode name": "PLAINFIELD, NJ",
    City: "PLAINFIELD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07062",
    "Zipcode name": "PLAINFIELD, NJ",
    City: "PLAINFIELD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07063",
    "Zipcode name": "PLAINFIELD, NJ",
    City: "PLAINFIELD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08536",
    "Zipcode name": "PLAINSBORO, NJ",
    City: "PLAINSBORO",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08232",
    "Zipcode name": "PLEASANTVILLE, NJ",
    City: "PLEASANTVILLE",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07978",
    "Zipcode name": "PLUCKEMIN, NJ",
    City: "PLUCKEMIN",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08742",
    "Zipcode name": "POINT PLEASANT BEACH, NJ",
    City: "POINT PLEASANT BEACH",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08240",
    "Zipcode name": "POMONA, NJ",
    City: "POMONA",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07442",
    "Zipcode name": "POMPTON LAKES, NJ",
    City: "POMPTON LAKES",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07444",
    "Zipcode name": "POMPTON PLAINS, NJ",
    City: "POMPTON PLAINS",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08348",
    "Zipcode name": "PORT ELIZABETH, NJ",
    City: "PORT ELIZABETH",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07758",
    "Zipcode name": "PORT MONMOUTH, NJ",
    City: "PORT MONMOUTH",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07865",
    "Zipcode name": "PORT MURRAY, NJ",
    City: "PORT MURRAY",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08349",
    "Zipcode name": "PORT NORRIS, NJ",
    City: "PORT NORRIS",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07064",
    "Zipcode name": "PORT READING, NJ",
    City: "PORT READING",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08241",
    "Zipcode name": "PORT REPUBLIC, NJ",
    City: "PORT REPUBLIC",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07979",
    "Zipcode name": "POTTERSVILLE, NJ",
    City: "POTTERSVILLE",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08540",
    "Zipcode name": "PRINCETON, NJ",
    City: "PRINCETON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08541",
    "Zipcode name": "PRINCETON, NJ",
    City: "PRINCETON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08542",
    "Zipcode name": "PRINCETON, NJ",
    City: "PRINCETON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08543",
    "Zipcode name": "PRINCETON, NJ",
    City: "PRINCETON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08544",
    "Zipcode name": "PRINCETON, NJ",
    City: "PRINCETON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08550",
    "Zipcode name": "PRINCETON JUNCTION, NJ",
    City: "PRINCETON JUNCTION",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08868",
    "Zipcode name": "QUAKERTOWN, NJ",
    City: "QUAKERTOWN",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08072",
    "Zipcode name": "QUINTON, NJ",
    City: "QUINTON",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "07065",
    "Zipcode name": "RAHWAY, NJ",
    City: "RAHWAY",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07446",
    "Zipcode name": "RAMSEY, NJ",
    City: "RAMSEY",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08073",
    "Zipcode name": "RANCOCAS, NJ",
    City: "RANCOCAS",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07869",
    "Zipcode name": "RANDOLPH, NJ",
    City: "RANDOLPH",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08869",
    "Zipcode name": "RARITAN, NJ",
    City: "RARITAN",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08870",
    "Zipcode name": "READINGTON, NJ",
    City: "READINGTON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07701",
    "Zipcode name": "RED BANK, NJ",
    City: "RED BANK",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07709",
    "Zipcode name": "RED BANK, NJ",
    City: "RED BANK",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08350",
    "Zipcode name": "RICHLAND, NJ",
    City: "RICHLAND",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08074",
    "Zipcode name": "RICHWOOD, NJ",
    City: "RICHWOOD",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07657",
    "Zipcode name": "RIDGEFIELD, NJ",
    City: "RIDGEFIELD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07660",
    "Zipcode name": "RIDGEFIELD PARK, NJ",
    City: "RIDGEFIELD PARK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07450",
    "Zipcode name": "RIDGEWOOD, NJ",
    City: "RIDGEWOOD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07451",
    "Zipcode name": "RIDGEWOOD, NJ",
    City: "RIDGEWOOD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08551",
    "Zipcode name": "RINGOES, NJ",
    City: "RINGOES",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07456",
    "Zipcode name": "RINGWOOD, NJ",
    City: "RINGWOOD",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "08242",
    "Zipcode name": "RIO GRANDE, NJ",
    City: "RIO GRANDE",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07661",
    "Zipcode name": "RIVER EDGE, NJ",
    City: "RIVER EDGE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07457",
    "Zipcode name": "RIVERDALE, NJ",
    City: "RIVERDALE",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08075",
    "Zipcode name": "RIVERSIDE, NJ",
    City: "RIVERSIDE",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08076",
    "Zipcode name": "RIVERTON, NJ",
    City: "RIVERTON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08077",
    "Zipcode name": "RIVERTON, NJ",
    City: "RIVERTON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07662",
    "Zipcode name": "ROCHELLE PARK, NJ",
    City: "ROCHELLE PARK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07866",
    "Zipcode name": "ROCKAWAY, NJ",
    City: "ROCKAWAY",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08553",
    "Zipcode name": "ROCKY HILL, NJ",
    City: "ROCKY HILL",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08554",
    "Zipcode name": "ROEBLING, NJ",
    City: "ROEBLING",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08555",
    "Zipcode name": "ROOSEVELT, NJ",
    City: "ROOSEVELT",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07068",
    "Zipcode name": "ROSELAND, NJ",
    City: "ROSELAND",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07203",
    "Zipcode name": "ROSELLE, NJ",
    City: "ROSELLE",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07204",
    "Zipcode name": "ROSELLE PARK, NJ",
    City: "ROSELLE PARK",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08556",
    "Zipcode name": "ROSEMONT, NJ",
    City: "ROSEMONT",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08352",
    "Zipcode name": "ROSENHAYN, NJ",
    City: "ROSENHAYN",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07760",
    "Zipcode name": "RUMSON, NJ",
    City: "RUMSON",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08078",
    "Zipcode name": "RUNNEMEDE, NJ",
    City: "RUNNEMEDE",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07070",
    "Zipcode name": "RUTHERFORD, NJ",
    City: "RUTHERFORD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07663",
    "Zipcode name": "SADDLE BROOK, NJ",
    City: "SADDLE BROOK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07458",
    "Zipcode name": "SADDLE RIVER, NJ",
    City: "SADDLE RIVER",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08079",
    "Zipcode name": "SALEM, NJ",
    City: "SALEM",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "08871",
    "Zipcode name": "SAYREVILLE, NJ",
    City: "SAYREVILLE",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08872",
    "Zipcode name": "SAYREVILLE, NJ",
    City: "SAYREVILLE",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07870",
    "Zipcode name": "SCHOOLEYS MOUNTAIN, NJ",
    City: "SCHOOLEYS MOUNTAIN",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07076",
    "Zipcode name": "SCOTCH PLAINS, NJ",
    City: "SCOTCH PLAINS",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08750",
    "Zipcode name": "SEA GIRT, NJ",
    City: "SEA GIRT",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08243",
    "Zipcode name": "SEA ISLE CITY, NJ",
    City: "SEA ISLE CITY",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08751",
    "Zipcode name": "SEASIDE HEIGHTS, NJ",
    City: "SEASIDE HEIGHTS",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08752",
    "Zipcode name": "SEASIDE PARK, NJ",
    City: "SEASIDE PARK",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07094",
    "Zipcode name": "SECAUCUS, NJ",
    City: "SECAUCUS",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07096",
    "Zipcode name": "SECAUCUS, NJ",
    City: "SECAUCUS",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "08557",
    "Zipcode name": "SERGEANTSVILLE, NJ",
    City: "SERGEANTSVILLE",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "07077",
    "Zipcode name": "SEWAREN, NJ",
    City: "SEWAREN",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08080",
    "Zipcode name": "SEWELL, NJ",
    City: "SEWELL",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08353",
    "Zipcode name": "SHILOH, NJ",
    City: "SHILOH",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "07078",
    "Zipcode name": "SHORT HILLS, NJ",
    City: "SHORT HILLS",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07702",
    "Zipcode name": "SHREWSBURY, NJ",
    City: "SHREWSBURY",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08081",
    "Zipcode name": "SICKLERVILLE, NJ",
    City: "SICKLERVILLE",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08558",
    "Zipcode name": "SKILLMAN, NJ",
    City: "SKILLMAN",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08083",
    "Zipcode name": "SOMERDALE, NJ",
    City: "SOMERDALE",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08244",
    "Zipcode name": "SOMERS POINT, NJ",
    City: "SOMERS POINT",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "08873",
    "Zipcode name": "SOMERSET, NJ",
    City: "SOMERSET",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08875",
    "Zipcode name": "SOMERSET, NJ",
    City: "SOMERSET",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08876",
    "Zipcode name": "SOMERVILLE, NJ",
    City: "SOMERVILLE",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08879",
    "Zipcode name": "SOUTH AMBOY, NJ",
    City: "SOUTH AMBOY",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08880",
    "Zipcode name": "SOUTH BOUND BROOK, NJ",
    City: "SOUTH BOUND BROOK",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08245",
    "Zipcode name": "SOUTH DENNIS, NJ",
    City: "SOUTH DENNIS",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07606",
    "Zipcode name": "SOUTH HACKENSACK, NJ",
    City: "SOUTH HACKENSACK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07079",
    "Zipcode name": "SOUTH ORANGE, NJ",
    City: "SOUTH ORANGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07080",
    "Zipcode name": "SOUTH PLAINFIELD, NJ",
    City: "SOUTH PLAINFIELD",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08882",
    "Zipcode name": "SOUTH RIVER, NJ",
    City: "SOUTH RIVER",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08246",
    "Zipcode name": "SOUTH SEAVILLE, NJ",
    City: "SOUTH SEAVILLE",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07871",
    "Zipcode name": "SPARTA, NJ",
    City: "SPARTA",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08884",
    "Zipcode name": "SPOTSWOOD, NJ",
    City: "SPOTSWOOD",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "07762",
    "Zipcode name": "SPRING LAKE, NJ",
    City: "SPRING LAKE",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07081",
    "Zipcode name": "SPRINGFIELD, NJ",
    City: "SPRINGFIELD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07874",
    "Zipcode name": "STANHOPE, NJ",
    City: "STANHOPE",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08885",
    "Zipcode name": "STANTON, NJ",
    City: "STANTON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08886",
    "Zipcode name": "STEWARTSVILLE, NJ",
    City: "STEWARTSVILLE",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07875",
    "Zipcode name": "STILLWATER, NJ",
    City: "STILLWATER",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07980",
    "Zipcode name": "STIRLING, NJ",
    City: "STIRLING",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07460",
    "Zipcode name": "STOCKHOLM, NJ",
    City: "STOCKHOLM",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08559",
    "Zipcode name": "STOCKTON, NJ",
    City: "STOCKTON",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08247",
    "Zipcode name": "STONE HARBOR, NJ",
    City: "STONE HARBOR",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08084",
    "Zipcode name": "STRATFORD, NJ",
    City: "STRATFORD",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08248",
    "Zipcode name": "STRATHMERE, NJ",
    City: "STRATHMERE",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07876",
    "Zipcode name": "SUCCASUNNA, NJ",
    City: "SUCCASUNNA",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07901",
    "Zipcode name": "SUMMIT, NJ",
    City: "SUMMIT",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07902",
    "Zipcode name": "SUMMIT, NJ",
    City: "SUMMIT",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07461",
    "Zipcode name": "SUSSEX, NJ",
    City: "SUSSEX",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07877",
    "Zipcode name": "SWARTSWOOD, NJ",
    City: "SWARTSWOOD",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08085",
    "Zipcode name": "SWEDESBORO, NJ",
    City: "SWEDESBORO",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07666",
    "Zipcode name": "TEANECK, NJ",
    City: "TEANECK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07670",
    "Zipcode name": "TENAFLY, NJ",
    City: "TENAFLY",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07763",
    "Zipcode name": "TENNENT, NJ",
    City: "TENNENT",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07608",
    "Zipcode name": "TETERBORO, NJ",
    City: "TETERBORO",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08086",
    "Zipcode name": "THOROFARE, NJ",
    City: "THOROFARE",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08887",
    "Zipcode name": "THREE BRIDGES, NJ",
    City: "THREE BRIDGES",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08560",
    "Zipcode name": "TITUSVILLE, NJ",
    City: "TITUSVILLE",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08753",
    "Zipcode name": "TOMS RIVER, NJ",
    City: "TOMS RIVER",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08754",
    "Zipcode name": "TOMS RIVER, NJ",
    City: "TOMS RIVER",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08755",
    "Zipcode name": "TOMS RIVER, NJ",
    City: "TOMS RIVER",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08756",
    "Zipcode name": "TOMS RIVER, NJ",
    City: "TOMS RIVER",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "08757",
    "Zipcode name": "TOMS RIVER, NJ",
    City: "TOMS RIVER",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07511",
    "Zipcode name": "TOTOWA, NJ",
    City: "TOTOWA",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07512",
    "Zipcode name": "TOTOWA, NJ",
    City: "TOTOWA",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07082",
    "Zipcode name": "TOWACO, NJ",
    City: "TOWACO",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07676",
    "Zipcode name": "TOWNSHIP OF WASHINGTON, NJ",
    City: "TOWNSHIP OF WASHINGTON",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07879",
    "Zipcode name": "TRANQUILITY, NJ",
    City: "TRANQUILITY",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "08641",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08601",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08602",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08603",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08604",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08605",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08606",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08607",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08608",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08609",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08610",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08611",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08618",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08619",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08620",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08625",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08628",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08629",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08638",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08646",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08647",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08650",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08666",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08690",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08691",
    "Zipcode name": "TRENTON, NJ",
    City: "TRENTON",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08250",
    "Zipcode name": "TUCKAHOE, NJ",
    City: "TUCKAHOE",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08087",
    "Zipcode name": "TUCKERTON, NJ",
    City: "TUCKERTON",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07083",
    "Zipcode name": "UNION, NJ",
    City: "UNION",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07087",
    "Zipcode name": "UNION CITY, NJ",
    City: "UNION CITY",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07088",
    "Zipcode name": "VAUXHALL, NJ",
    City: "VAUXHALL",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08406",
    "Zipcode name": "VENTNOR CITY, NJ",
    City: "VENTNOR CITY",
    State: "NJ",
    "County Name": "ATLANTIC",
  },
  {
    zip: "07462",
    "Zipcode name": "VERNON, NJ",
    City: "VERNON",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07044",
    "Zipcode name": "VERONA, NJ",
    City: "VERONA",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07880",
    "Zipcode name": "VIENNA, NJ",
    City: "VIENNA",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "08251",
    "Zipcode name": "VILLAS, NJ",
    City: "VILLAS",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08088",
    "Zipcode name": "VINCENTOWN, NJ",
    City: "VINCENTOWN",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08360",
    "Zipcode name": "VINELAND, NJ",
    City: "VINELAND",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08361",
    "Zipcode name": "VINELAND, NJ",
    City: "VINELAND",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08362",
    "Zipcode name": "VINELAND, NJ",
    City: "VINELAND",
    State: "NJ",
    "County Name": "CUMBERLAND",
  },
  {
    zip: "08043",
    "Zipcode name": "VOORHEES, NJ",
    City: "VOORHEES",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07463",
    "Zipcode name": "WALDWICK, NJ",
    City: "WALDWICK",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07057",
    "Zipcode name": "WALLINGTON, NJ",
    City: "WALLINGTON",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07881",
    "Zipcode name": "WALLPACK CENTER, NJ",
    City: "WALLPACK CENTER",
    State: "NJ",
    "County Name": "SUSSEX",
  },
  {
    zip: "07465",
    "Zipcode name": "WANAQUE, NJ",
    City: "WANAQUE",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "08758",
    "Zipcode name": "WARETOWN, NJ",
    City: "WARETOWN",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07059",
    "Zipcode name": "WARREN, NJ",
    City: "WARREN",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "07882",
    "Zipcode name": "WASHINGTON, NJ",
    City: "WASHINGTON",
    State: "NJ",
    "County Name": "WARREN",
  },
  {
    zip: "07069",
    "Zipcode name": "WATCHUNG, NJ",
    City: "WATCHUNG",
    State: "NJ",
    "County Name": "SOMERSET",
  },
  {
    zip: "08089",
    "Zipcode name": "WATERFORD WORKS, NJ",
    City: "WATERFORD WORKS",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07470",
    "Zipcode name": "WAYNE, NJ",
    City: "WAYNE",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07474",
    "Zipcode name": "WAYNE, NJ",
    City: "WAYNE",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07086",
    "Zipcode name": "WEEHAWKEN, NJ",
    City: "WEEHAWKEN",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "08090",
    "Zipcode name": "WENONAH, NJ",
    City: "WENONAH",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08091",
    "Zipcode name": "WEST BERLIN, NJ",
    City: "WEST BERLIN",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "08092",
    "Zipcode name": "WEST CREEK, NJ",
    City: "WEST CREEK",
    State: "NJ",
    "County Name": "OCEAN",
  },
  {
    zip: "07764",
    "Zipcode name": "WEST LONG BRANCH, NJ",
    City: "WEST LONG BRANCH",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "07480",
    "Zipcode name": "WEST MILFORD, NJ",
    City: "WEST MILFORD",
    State: "NJ",
    "County Name": "PASSAIC",
  },
  {
    zip: "07093",
    "Zipcode name": "WEST NEW YORK, NJ",
    City: "WEST NEW YORK",
    State: "NJ",
    "County Name": "HUDSON",
  },
  {
    zip: "07052",
    "Zipcode name": "WEST ORANGE, NJ",
    City: "WEST ORANGE",
    State: "NJ",
    "County Name": "ESSEX",
  },
  {
    zip: "07090",
    "Zipcode name": "WESTFIELD, NJ",
    City: "WESTFIELD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "07091",
    "Zipcode name": "WESTFIELD, NJ",
    City: "WESTFIELD",
    State: "NJ",
    "County Name": "UNION",
  },
  {
    zip: "08093",
    "Zipcode name": "WESTVILLE, NJ",
    City: "WESTVILLE",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07675",
    "Zipcode name": "WESTWOOD, NJ",
    City: "WESTWOOD",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "07885",
    "Zipcode name": "WHARTON, NJ",
    City: "WHARTON",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "07981",
    "Zipcode name": "WHIPPANY, NJ",
    City: "WHIPPANY",
    State: "NJ",
    "County Name": "MORRIS",
  },
  {
    zip: "08888",
    "Zipcode name": "WHITEHOUSE, NJ",
    City: "WHITEHOUSE",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08889",
    "Zipcode name": "WHITEHOUSE STATION, NJ",
    City: "WHITEHOUSE STATION",
    State: "NJ",
    "County Name": "HUNTERDON",
  },
  {
    zip: "08252",
    "Zipcode name": "WHITESBORO, NJ",
    City: "WHITESBORO",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07765",
    "Zipcode name": "WICKATUNK, NJ",
    City: "WICKATUNK",
    State: "NJ",
    "County Name": "MONMOUTH",
  },
  {
    zip: "08260",
    "Zipcode name": "WILDWOOD, NJ",
    City: "WILDWOOD",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "08094",
    "Zipcode name": "WILLIAMSTOWN, NJ",
    City: "WILLIAMSTOWN",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "08046",
    "Zipcode name": "WILLINGBORO, NJ",
    City: "WILLINGBORO",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "08561",
    "Zipcode name": "WINDSOR, NJ",
    City: "WINDSOR",
    State: "NJ",
    "County Name": "MERCER",
  },
  {
    zip: "08095",
    "Zipcode name": "WINSLOW, NJ",
    City: "WINSLOW",
    State: "NJ",
    "County Name": "CAMDEN",
  },
  {
    zip: "07075",
    "Zipcode name": "WOOD RIDGE, NJ",
    City: "WOOD RIDGE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08270",
    "Zipcode name": "WOODBINE, NJ",
    City: "WOODBINE",
    State: "NJ",
    "County Name": "CAPE MAY",
  },
  {
    zip: "07095",
    "Zipcode name": "WOODBRIDGE, NJ",
    City: "WOODBRIDGE",
    State: "NJ",
    "County Name": "MIDDLESEX",
  },
  {
    zip: "08097",
    "Zipcode name": "WOODBURY HEIGHTS, NJ",
    City: "WOODBURY HEIGHTS",
    State: "NJ",
    "County Name": "GLOUCESTER",
  },
  {
    zip: "07677",
    "Zipcode name": "WOODCLIFF LAKE, NJ",
    City: "WOODCLIFF LAKE",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08098",
    "Zipcode name": "WOODSTOWN, NJ",
    City: "WOODSTOWN",
    State: "NJ",
    "County Name": "SALEM",
  },
  {
    zip: "08562",
    "Zipcode name": "WRIGHTSTOWN, NJ",
    City: "WRIGHTSTOWN",
    State: "NJ",
    "County Name": "BURLINGTON",
  },
  {
    zip: "07481",
    "Zipcode name": "WYCKOFF, NJ",
    City: "WYCKOFF",
    State: "NJ",
    "County Name": "BERGEN",
  },
  {
    zip: "08890",
    "Zipcode name": "ZAREPHATH, NJ",
    City: "ZAREPHATH",
    State: "NJ",
    "County Name": "SOMERSET",
  },
];
